# -*- coding: utf-8 -*-
"""Week 5 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IY3Gxqw6QHB7ew3HMRk93Mk_r0F4dom
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from pycaret.classification import *


df = pd.read_csv('/content/workingdata.csv', index_col='customerID')

# Cleaning Datas
# Replace infinite values with NaN
df = df.replace([np.inf, -np.inf], np.nan)
if 'Unnamed: 0' in df.columns:
    df.drop(['Unnamed: 0'], axis=1, inplace=True)

# Drop rows with missing values in the 'Churn' column
df.dropna(subset=['Churn'], inplace=True)

# Proceed with PyCaret setup
automl = setup(data=df, target='Churn')

best_model = compare_models()

best_model

predict_model(best_model, df.iloc[-2:-1])

# Save the model to disk
save_model(best_model, 'SN_model')

import pickle

with open('SN_model.pk', 'wb') as f:
    pickle.dump(best_model, f)

with open('SN_model.pk', 'rb') as f:
    loaded_model = pickle.load(f)

new_data = df.iloc[-2:-1].copy()
loaded_model = load_model('SN_model')

"""**Summary:**
An attempt was made to use the pycaret to find a ML algorithm to fit in the data. Different metrics were utilized for finding the best model among which I have utilized the regression. The model SN_model was saved to the disk along with a python script. The error arised while predicting with the new churn data set as some of the columns were not fitted. The python script is then subjected to be uploaded in the GitHub repository.
"""